---
title: "Observation Wells Groundwater Levels"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: true
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{caption}
  - \usepackage[normalem]{ulem}
  - \usepackage[utf8]{inputenc}
  - \usepackage{makecell}
  - \usepackage{xcolor}
  - \usepackage{pdflscape}
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
params: 
  w_full: ""
  w_hist: ""
  w_comp: ""
  w_perc: ""
  w_dates: ""
  report_dates: ""
  within: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.kable.NA = '')
w_full <- params$w_full
w_hist <- params$w_hist
w_comp <- params$w_comp
w_perc <- params$w_perc
w_dates <- params$w_dates
within <- params$within
report_dates <- params$report_dates
ows <- unique(w_full$ow)
```

## Section 1 - Overview


```{r table_1}
w_dates %>%
  well_meta() %>%
  mutate(ow = ow_link(ow),
         area_name = str_remove_all(area_name, "( Natural Resource )|(Region)|(Area)"),
         district_name = str_remove(district_name, " Natural Resource District"),
         Value = as.character(round(Value, 2)),
         Value = if_else(Date != report_dates & !is.na(Value), 
                         as.character(glue("{Value}*")),
                         Value)) %>%
  arrange(area_name, district_name, ow, desc(Date)) %>%
  select(area_name, district_name, ow, Value, report_dates) %>%
  pivot_wider(names_from = "report_dates", values_from = "Value") %>%
  rename(Region = area_name, `Geographic\nArea` = district_name, `Obs.\nWell` = ow) %>%
  kable(booktabs = TRUE, longtable = TRUE, format = "latex", digits = 2, linesep = "",
        escape = FALSE,
        caption = glue("\\textbf{{Well numbers and reporting dates}}\\\\",
                       "Values are depth below ground (m) for a given well/date.\\\\",
                       "Blank cells indicate no data.\\\\",
                       "** indicates a value not on the exact reporting date but within a {within*2}-day window around ",
                       "the reporting date.")) %>%
  kable_styling(latex_options = c("hold_position", "repeat_header"))
```

\newpage

### Wells Below Normal

```{r table_2}
window <- w_perc %>%
  filter(window) %>%
  pull(report_dates) %>%
  unique()

totals <- w_perc %>%
  select(-type) %>%
  filter(str_detect(class, "low")) %>%
  group_by(report_dates) %>%
  summarize(t = unique(n_total_date), 
            n = sum(n_class_type),
            p = round(n / t * 100),
            p = if_else(is.nan(p), 0, p), .groups = "drop") %>%
  mutate(text = glue("{p}% ({n}/{t})"),
         text = if_else(t == 0, glue(""), text)) %>%
  select(report_dates, text) %>%
  arrange(desc(report_dates)) %>%
  mutate(type = "Across all types")

t <- w_perc %>%
  filter(str_detect(class, "low")) %>%
  group_by(report_dates, type) %>%
  summarize(t = unique(n_total_type), n = sum(n_class_type),
            p = round(n / t * 100),
            p = if_else(is.nan(p), 0, p),
            .groups = "drop") %>%
  mutate(text = glue("{p}% ({n}/{t})"), 
         text = if_else(t == 0, glue(""), text)) %>%
  select(report_dates, type, text) %>%
  arrange(desc(report_dates)) %>%
  bind_rows(totals) %>%
  mutate(report_dates = if_else(report_dates %in% window, 
                                as.character(glue("{report_dates}*")), 
                                as.character(report_dates))) %>%
  pivot_wider(names_from = report_dates, values_from = text) %>%
  select(type, everything())

t %>%
  rename(`Aquifer Type` = type) %>%
  kable(format = "latex", booktabs = TRUE, linesep = "",
        caption = glue("\\textbf{{Proportion of wells Below Normal or Much Below Normal}}\\\\",
                       "(X/Y) indicates X wells with low values out of Y wells total for that ",
                       "date/category.\\\\",
                       "Blank cells indicate no wells with data\\\\",
                       "** indicates reporting dates which include values within ",
                       "a {within*2}-day window around it")) %>%
  kable_styling(latex_options = "hold_position") %>%
  row_spec(str_which(t$type, "Across all types"), hline_after = TRUE)
```

### Groundwater Level Status
```{r table_3}
t <- w_perc %>%
  select(class, report_dates, n_total_class, n_total_date) %>%
  distinct() %>%
  arrange(desc(report_dates)) %>%
  pivot_longer(cols = contains("total"), names_to = "total", values_to = "n") %>%
  mutate(class = if_else(str_detect(total, "date"), "Across all classes", class),
         class = factor(class, levels = c(perc_values$nice, "Across all classes"))) %>%
  select(-total) %>%
  distinct() %>%
  mutate(report_dates = if_else(report_dates %in% window, 
                                as.character(glue("{report_dates}*")), 
                                as.character(report_dates))) %>%
  pivot_wider(names_from = report_dates, values_from = n) %>%
  arrange(class) %>%
  left_join(select(perc_values, colour, nice), by = c("class" = "nice")) %>%
  mutate(colour = replace_na(colour, "white")) %>%
  select(colour, class, everything())

t %>%
  mutate(colour = "") %>%
  kable(format = "latex", col.names = c(" ", "Percentile class", names(.)[-c(1:2)]), 
        booktabs = TRUE, linesep = "",
        caption = glue("\\textbf{{Number of wells in each percentile class ",
                       "by date}}\\\\",
                       "** indicates reporting dates which include values within ",
                       "a {within*2}-day window around it")) %>%
  kable_styling(latex_options = "hold_position") %>%
  column_spec(1, background = c("white", t$colour)) %>%
  row_spec(str_which(t$class, "Across"), hline_after = TRUE)
```

\newpage

\blandscape
## Section 2 - Summary

\captionsetup{width=0.9\paperwidth}

```{r table_4}
t <- well_hist_compare(w_dates, w_full)

last_year <- t %>%
  filter(!CurrentYear) %>%
  select(ow, value_last_year = Value, report_dates) %>%
  mutate(report_dates = report_dates + years(1))
  
t <- t %>%
  well_meta() %>%
  arrange(ow, desc(Date)) %>%
  group_by(ow) %>%
  filter(CurrentYear) %>%
  mutate(keep = if_else(all(is.na(Value)), Date[1], Date[!is.na(Value)][1])) %>%
  filter(Date == keep) %>%
  left_join(last_year, by = c("ow", "report_dates")) %>%
  mutate(ow = ow_link(ow),
         class = map_chr(percentile, perc_match, cols = "nice"),
         Name = "", 
         area_name = str_remove_all(area_name, "( Natural Resource )|(Region)|(Area)"),
         district_name = str_remove(district_name, "Natural Resource District"), 
         Value = as.character(round(Value, 2)), 
         Value = if_else(Approval == "Working" & !is.na(Value), as.character(glue("{Value}*")), Value),
         value_last_year = round(value_last_year, 2),
         class = replace_na(class, ""),
         percentile = if_else(is.na(percentile), glue(""), glue(" ({round((1 - percentile) * 100)}\\%)")),
         percentile = glue("{class}{percentile}"),
         median = round(median, 2)) %>%
  ungroup() %>%
  arrange(area_name, district_name, ow)

bg_colour <- set_names(perc_values$colour, perc_values$nice)[t$class]
bg_colour <- replace_na(bg_colour, "white")
txt_colour <- set_names(perc_values$txt_colour, perc_values$nice)[t$class]
txt_colour <- replace_na(txt_colour, "black")
                        
t <- t %>%
  select(Region = area_name, `Geographic\nArea` = district_name, Name, 
         `Obs.\nWell` = ow, `Aquifer Type` = type, 
         `Latest\nDate` = Date, `Latest\nValue` = Value, 
         `Percentile Class` = percentile,
         `Last Year's\nValue` = value_last_year, Median = median)

t %>%
  kable(format = "latex", booktabs = TRUE, longtable = TRUE, escape = FALSE, linesep = "",
        col.names = linebreak(names(t), align = "c"), align = "lllllcrcrr",
        caption = glue("\\textbf{{Information on observation wells in ",
                       "{year(t$`Latest\nDate`[1])}}}\\\\", 
                       "Includes comparison of latest water depth value ",
                       "compared to last year's value. ",
                       "Values/Medians are in meters below ground.\\\\",
                       "** Indicates an Approval Status of 'Working'")) %>%
  kable_styling(latex_options = c("hold_position", "repeat_header")) %>%
  column_spec(str_which(names(t), "Aquifer Type"), width = "7em", latex_valign = "m") %>%
  column_spec(str_which(names(t), "Percentile Class"), width = "8em", latex_valign = "m", 
              background = bg_colour, color = txt_colour)
```

\elandscape


\newpage

## Section 3 -  Plots

```{r s3_obs_well_plots, results = "asis", fig.asp = 1.25, fig.width = 10}
date_range <- w_full %>%
  filter(CurrentYear) %>%
  select(WaterYear, water_year_start) %>%
  distinct() %>%
  glue_data("{WaterYear}-{water_year_start}-01") %>%
  ymd()
date_range <- c(date_range - years(20), date_range)

latest_date <- w_dates %>% 
  group_by(ow) %>% 
  filter(!is.na(Value)) %>%
  filter(Date == max(Date))

for(ow in ows) {
  cat(glue("### {ow}\n\n"))
  full <- filter(w_full, ow == !!ow)
  hist <- filter(w_hist, ow == !!ow)
  date <- filter(latest_date, ow == !!ow)
  
  g1 <- well_plot_perc(full, hist, date)
  g2 <- well_plot_hist(full, hist, date_range, date, wrap_year = TRUE)
  
  g <- g1 / g2 + plot_layout(heights = c(1, 2))
  print(g)
  
  cat("\n\n\\newpage\n\n")
}
```




